# autocode configuration
autocode:
  transfer-restart: true
  # root 自动适配项目根目录
  # 请不要手动配置,他会在项目加载的时候识别出根路径
  root: ""
  server: /server
  server-plug: /plugin/%s
  server-api: /api/v1/%s
  server-initialize: /initialize
  server-model: /model/%s
  server-request: /model/%s/request/
  server-router: /router/%s
  server-service: /service/%s
  web: /web/src
  web-api: /api
  web-form: /view
  web-table: /view

zap:
  level: info
  format: console
  prefix: zzk
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

system:
  env: public
  addr: 8888
  db-type: mysql
  oss-type: local
  use-redis: false
  use-multipoint: false
  # IP 限制次数 一个小时15000次
  iplimit-count: 15000
  # IP限制一个小时
  iplimit-time: 3600

mysql:
  path: "127.0.0.1"
  port: "3306"
  config: ""
  db-name: "mangoblog"
  username: "root"
  password: "123456"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

# 定时任务 github.com/robfig/cron/v3@v3.0.0
Timer:
  start: true
  spec: "@daily"
  detail:
    - tableName: sys_operation_records
      compareField: created_at
      interval: 2160h
    - tableName: jwt_blacklists
      compareField: created_at
      interval: 168h

db-list:
  - disable: true
    type: "mysql" # 数据库类型
    alias-name: "" # 数据库名称

jwt:
  # 签名密钥
  signing-key: mgBlog
  # 有效时间
  expires-time: 7d
  # 缓冲时间
  buffer-time: 1d
  # 发行人
  issuer: mango

captcha:
  #  验证码长度
  key-long: 6
  # 图片宽度
  img-width: 240
  # 图片高度
  img-height: 80
  # 图片最大倾斜
  max-skew: 0.7
  # 图片浮点数
  dot-count: 80
